In [2]:
import numpy as np                # basic arrays, vectors, matrices
import scipy as sp                # matrix linear algebra 

import matplotlib                 # plotting
import matplotlib.pyplot as plt   # plotting

from sklearn import preprocessing

%matplotlib inline

from IPython.core.display import HTML
HTML("""<style>.output_png { display: table-cell; text-align: center; vertical-align: middle; }</style>""");

In [29]:
A = np.array([[9, 0, 3], [4, 6, 12], [15, 9, 3]])
n = len(A)
b = np.random.rand(n)

c = np.array([2, 4, 6])

print(A)
print(c)

Mul = np.matmul(A, c)

norm = sum(np.sqrt(Mul**2))
print(norm)

print(Mul)

mu = (c.T@Mul)/(c.T@c)
d = c.T
print(d)
print(mu)

for i in range(3, 10):
        
    mu = np.zeros(i)
print(mu)

[[ 9  0  3]
 [ 4  6 12]
 [15  9  3]]
[2 4 6]
224.0
[ 36 104  84]
[2 4 6]
17.714285714285715
[0. 0. 0. 0. 0. 0. 0. 0. 0.]


In [30]:
def power_iteration(A, maxiter = 50):
    """perform power iteration on A and return the sequence of Rayleigh coefficients"""
    # TODO 
    n = len(A)
    b = np.random.rand(n)

    for i in range(maxiter):
        
        #Mul = np.zeros(i)
        #mu = np.zeros(i)
        
        Mul = np.matmul(A, b)
        b = Mul/sum(np.sqrt(Mul**2))
        
        mu = (b.T@Mul)/(b.T@b)
        
        
        
    return mu,b

In [31]:
A = np.array([[9, 0, 3], [4, 6, 12], [15, 9, 3]])

mu, b = power_iteration(A)

In [33]:
b

array([0.13636364, 0.45454545, 0.40909091])